### ISSUE TITLE
Error loading preference bundle 😵

### ISSUE THREAD

**Issue by sharklatan** [LaughingQuoll/Semperon#3]
iPhone7,2 11.3.1

**Comment by raydelvalle** [comment]
Everything installs good but then in settings there is no  configuration  panel and it says something about APT error with Cydia two things wasn’t installed correctly any help here ?

**Comment by raydelvalle** [comment]
Got a fix there is updates in Cydia for Tweak Injector and substrate go and update those reinstall the tweak BOOM! It works
